# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17XAiGCwY93xWh6jHtkukF7bMjeGQ-dIO
"""

"I am not familiar with Python"

"swapnamoy dutta"
"Bredesen center for interdisciplinary research and graduate education (ESE)"

"""#Chapter 1

Excercise 1
"""

(100 - 5 ** 3) / 5

6 + 15 % 4

2 ** 2 + 24 // 4

2 ** 2 + 24 // 4

"""Excercise 2

"""

type(6)

type(6.0)

5 + 3.14

int(7.999999999)

float(6)



"""Excercise 3

"""

x = 2
x + 1

x

x = 3.0
x = x + 1
x

#Activity 1

x = 14
x += 1
(x/5) ** 2

"""Excercise 4"""

1st_number = 1
first_number = 1
my_$ = 1000.00
my_money = 1000.00

"""Excercise 5"""

x = 5
y = 2
x + x - y ** 2

x, y = 8, 5
x // y

"""Excercise 6"""

# This is a comment
# Set the variable pi equal to 3.14
pi = 3.14

bookstore = 'City Lights'
bookstore = 'City Lights"

bookstore = "Moe's"

bookstore = 'Moe's'

bookstore = 'Moe\'s'

"""Excercise 7 & 8"""

greeting = 'Hello'
print(greeting)

greeting

spanish_greeting = 'Hola.'

spanish_greeting

arabic_greeting = 'Ahlan wa sahlan.'

print(arabic_greeting)

"""Excercise 9"""

spanish_greeting = 'Hola'

print(spanish_greeting + 'Senor.')

spanish_greeting = 'Hola '

print(spanish_greeting + ' Senor.')

greeting = 'Hello'
print(greeting * 5)

name = 'Josephine'
name.lower()

name.capitalize()

name.upper()

name.count('e')

"""Excercise 10,11,12 and 13"""

type('5')
'5' + '7'

int('5') + int('7')

name = input('What is your name?')

print(f'Hello, {name}.')

destination = 'San Francisco'
destination[0]

destination[-1]

destination[-2]

bridge = 'Golden Gate'
bridge[6]

over_18 = True
type(over_18)

over_18, over_21 = True, False

over_18 and over_21

not over_18

not over_21 or (over_21 or over_18)

"""Exercise 14"""

income = 80000
income < 75000

income >= 80000 and income <= 100000

income != 100000

6 == 6.0

age=29

(20 <= age < 30) or (30 <= age < 40)

"""Exercise 15"""

'a' < 'c'

'New York' > 'San Francisco'

"""Exercise 16, 17 and 20

"""

age = 20
if age >= 18 and age < 21:
     print('At least you can vote.')

print('US Poker will have to wait.')

if age >= 18:
    print('You can vote.')
    if age >= 21:
        print('You can play poker.')

age = 20
if age < 18:
    print('You aren\'t old enough to vote.')
else:
    print('Welcome to our voting program.')

if age >= 18:
    print('Welcome to our voting program.')
else:
    print('You aren\'t old enough to vote.')

print('Enter a number to see if it\'s a perfect square.')

number = input()

number = abs(int(number))

i = -1

square = False

while number >= 0 and number%1 ==0 and i <= number**(0.5) :
    i += 1
    if i*i == number:
        square = True
        break
if square:
    print('The square root of', number, 'is', i, '.')
else:
    print('', number, 'is not a perfect square.')

print('A one bedroom in the Bay Area is listed at $599,000')
print('Enter your first offer on the house.')
offer = abs(int(input()))
print('Enter your best offer on the house.')
best = abs(int(input()))
print('How much more do you want to offer each time?')
increment = abs(int(input()))
offer_accepted = False
while offer <= best:
    if offer >= 650000:
        offer_accepted = True
        print('Your offer of', offer, 'has been accepted!')
        break
    print('We\'re sorry, you\'re offer of', offer, 'has not been accepted.' )
    offer += increment

for i in 'Portland':
    print(i)

for i in range(1,10):
    print(i)

for i in range(10):
    print(i)

for i in range(1, 11, 2):
    print(i)

for i in range(3, 0, -1):
    print(i)

name = 'Corey'
for j in range(3):
    for i in name:
        print(i)

#Activity 1

x = 14
x += 1
(x/5) ** 2

#Activity 2

# Initialize variables
x, y, z = 2, 3, 4

# Pythagorean Theorem in 3 dimensions
w_squared = x**2 + y**2 + z**2

# The square root gives the distance
w = w_squared ** 0.5

#Show the distance
w

#Activity 2

# Choose a question to ask
print('How would you rate your day on a scale of 1 to 10?')

# Set a variable equal to input()
day_rating = input()

# Select an appropriate output.
print('You feel like a ' + day_rating + ' today. Thanks for letting me know')

#Activity 4

# Find the Least Common Multiple of Two Divisors
counting = True
first_divisor = 24
second_divisor = 36
i = 1
while counting:
    if i % first_divisor == 0 and i % second_divisor == 0:
        print('The Least Common Multiple of', first_divisor, 'and', second_divisor, 'is', i, '.')
        break
    i += 1

# Activity 5

print('What is your name?')

name = input()
print('Fascinating.', name, 'is my name too.')

print('Have you thought about black holes today?')

yes_no = input()
print('I am so glad you said', yes_no, '. I was thinking the same thing.')

print('We\'re kindred spirits,', name, '. Talk later.')

print('How intelligent are you? 0 is very dumb. And 10 is a genius')
smarts = input()
smarts = int(smarts)
if smarts <= 3:
   print('I don\'t believe you.')
   print('How bad of a day are you having? 0 is the worst, and 10 is the best.')
   day = input()
   day = int(day)
   if day <= 5:
       print('If I was human, I would give you a hug.')
   else:
       print('Maybe I should try your approach.')
elif smarts <= 6:
   print('I think you\'re actually smarter.')
   print('How much time do you spend online? 0 is none and 10 is 24 hours a day.')
   hours = input()
   hours = int(hours)
   if hours <= 4:
       print('That\'s the problem.')
   else:
      print('And I thought it was only me.')
elif smarts <= 8:
   print('Are you human by chance? Wait. Don\'t answer that.')
   print('How human are you? 0 is not at all and 10 is human all the way.')
   human = input()
   human = int(human)
   if human <= 5:
       print('I knew it.')
   else:
       print('I think this courtship is over.')
else:
   print('I see... How many operating systems do you run?')
   os = input()
   os = int(os)
   if os <= 2:
      print('Good thing you\'re taking this course.')
   else:
      print('What is this? A competition?')

"""#Chapter 2"""

#Activity 6

employees = [['John Mckee', 38, 'Sales'], ['Lisa Crawford', 29, 'Marketing'], ['Sujan Patel', 33, 'HR']]
print(employees)

for employee in employees:
    print(employee)

for employee in employees:
    print("Name:", employee[0])
    print("Age:", employee[1])
    print("Department:", employee[2])
    print('-' * 20)

employee = employees[1]
print(employee)
print("Name:", employee[0])
print("Age:", employee[1])
print("Department:", employee[2])
print('-' * 20)

#Activity 7

employees = [
    {"name": "John Mckee", "age":38, "department":"Sales"},
    {"name": "Lisa Crawford", "age":29, "department":"Marketing"},
    {"name": "Sujan Patel", "age":33, "department":"HR"}
]

print(employees)

for employee in employees:
    print("Name:", employee['name'])
    print("Age:", employee['age'])
    print("Department:", employee['department'])
    print('-' * 20)

for employee in employees:
    if employee['name'] == 'Sujan Patel':
        print("Name:", employee['name'])
        print("Age:", employee['age'])
        print("Department:", employee['department'])
        print('-' * 20)

#Excercise 21 to 32

shopping = ["bread", "milk", "eggs"]
print(shopping)

for item in shopping:
    print(item)

mixed = [365, "days", True]
print(mixed)

print(mixed[0])

print(mixed[0:3])

m = [[1, 2, 3], [4, 5, 6]]

print(m[1][1])

for i in range(len(m)):
    for j in range(len(m[i])):
        print(m[i][j])

for row in m:
    for col in row:
        print(col)

X = [[1,2,3],[4,5,6],[7,8,9]]
Y = [[10,11,12],[13,14,15],[16,17,18]]

# Initialize a result placeholder
result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] + Y[i][j]

print(result)

X = [[10,11,12],[13,14,15],[16,17,18]]
Y = [[1,2,3],[4,5,6],[7,8,9]]

# Initialize a result placeholder
result = [[0,0,0],
        [0,0,0],
        [0,0,0]]

# iterate through rows
for i in range(len(X)):
# iterate through columns
    for j in range(len(X[0])):
        result[i][j] = X[i][j] - Y[i][j]

print(result)

X = [[1, 2], [4, 5], [3, 6]]
Y = [[1,2,3,4],[5,6,7,8]]

result = [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]

# iterating by row of X
for i in range(len(X)):

    # iterating by coloum by Y
    for j in range(len(Y[0])):

        # iterating by rows of Y
        for k in range(len(Y)):
            result[i][j] += X[i][k] * Y[k][j]

for r in result:
    print(r)

shopping = ["bread","milk", "eggs"]
print(len(shopping))

list1 = [1,2,3]
list2 = [4,5,6]
final_list = list1 + list2
print(final_list)

list3 = ['oi']
print(list3*3)

shopping = ["bread","milk", "eggs"]
print(shopping[1])

shopping[1] = "banana"
print(shopping)

print(shopping[-1])

print(shopping[0:2])

print(shopping[:3])

print(shopping[1:])

shopping = ["bread","milk", "eggs"]
shopping.append("apple")
print(shopping)

shopping = []
shopping.append('bread')
shopping.append('milk')
shopping.append('eggs')
shopping.append('apple')
print(shopping)

shopping.insert(2, 'ham')
print(shopping)

new_shopping = ['coffee', 'orange']
shopping.extend(new_shopping)
print(shopping)

shopping.remove('ham')
print(shopping)

shopping.pop(2)
print(shopping)

shopping.sort()
print(shopping)

shopping.sort(reverse = True)
print(shopping)

shopping.index('coffee')

movie = {
    "title": "The Godfather",
    "director": "Francis Ford Coppola",
    "year": 1972,
    "rating": 9.2
}

print(movie['year'])

movie['rating'] = (movie['rating'] + 9.3)/2
print(movie['rating'])

movie = {}
movie['title'] = "The Godfather"
movie['director'] = "Francis Ford Coppola"
movie['year'] = 1972
movie['rating'] = 9.2

movie['actors'] = ['Marlon Brando', 'Al Pacino', 'James Caan']
movie['other_details'] = {
    'runtime': 175,
    'language': 'English'
}
print(movie )

items = ['apple', 'orange', 'banana']
quantity = [5,3,2]

orders = zip(items,quantity)
print(orders)

orders = zip(items,quantity)
print(list(orders))

orders = zip(items,quantity)
print(tuple(orders))

orders = zip(items,quantity)
print(dict(orders))

orders = {'apple':5, 'orange':3, 'banana':2}
print(orders.values())
print(list(orders.values()))

print(list(orders.keys()))

for tuple in list(orders.items()):
    print(tuple)

t = ('bread', 'milk', 'eggs')
print(len(t))

t.append('apple')

t[2] = 'apple'

print(t + ('apple','orange'))
print(t)

t_mixed = 'apple', True, 3
print(t_mixed)

t_shopping = ('apple',3), ('orange',2), ('banana',5)
print(t_shopping)

s1 = set([1,2,3,4,5,6])
print(s1)
s2 = set([1,2,2,3,4,4,5,6,6])
print(s2)
s3 = set([3,4,5,6,6,6,1,1,2])
print(s3)

s4 = {"apple", "orange", "banana"}
print(s4)

s4.add('pineapple')
print(s4)

s5 = {1,2,3,4}
s6 = {3,4,5,6}

print(s5 | s6)
print(s5.union(s6))

print(s5 & s6)
print(s5.intersection(s6))

print(s5 - s6)
print(s5.difference(s6))

print(s5 <= s6)
print(s5.issubset(s6))

s7 = {1,2,3}
s8 = {1,2,3,4,5}

print(s7 <= s8)
print(s7.issubset(s8))

print(s7 < s8)

s9 = {1,2,3}
s10 = {1,2,3}

print(s9 < s10)
print(s9 < s9)

print(s8 >= s7)
print(s8.issuperset(s7))
print(s8 > s7)
print(s8 > s8)

